export type ValidSkills =
  | "Python"
  | "FastAPI"
  | "Flask"
  | "Django"
  | "Go"
  | "Java"
  | "C++"
  | "TypeScript"
  | "JavaScript"
  | "HTML5"
  | "CSS3"
  | "React"
  | "Angular"
  | "Redux"
  | "Node.js"
  | "REST APIs"
  | "GraphQL"
  | "Microservices"
  | "Async Programming"
  | "PostgreSQL"
  | "MySQL"
  | "MongoDB"
  | "Redis"
  | "Elasticsearch"
  | "DynamoDB"
  | "SQL Server"
  | "Oracle"
  | "SQL"
  | "NoSQL"
  | "Docker"
  | "Kubernetes"
  | "Helm"
  | "AWS"
  | "Azure"
  | "GCP"
  | "Terraform"
  | "Jenkins"
  | "GitHub Actions"
  | "GitLab CI/CD"
  | "CI/CD"
  | "Kafka"
  | "Spark Structured Streaming"
  | "Airflow"
  | "dbt"
  | "DuckDB"
  | "Data Quality"
  | "CDC"
  | "Machine Learning"
  | "PyTorch"
  | "TensorFlow"
  | "Scikit-learn"
  | "Pandas"
  | "NumPy"
  | "LangChain"
  | "NLP"
  | "Transformers"
  | "CUDA"
  | "TensorRT"
  | "OAuth2"
  | "JWT"
  | "Postman"
  | "Grafana"
  | "ELK Stack"
  | "Bash"
  | "Git"
  | "PyTest"
  | "System Design"
  | "Distributed Systems"
  | "Chart.js"
  | "Gemini"
  | "RenderCV";

export type ValidCategory =
  | "Full Stack"
  | "Backend"
  | "Data Engineering"
  | "AI/ML"
  | "DevOps"
  | "Frontend";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "about"
  | "skills"
  | "projects"
  | "experience"
  | "education"
  | "contact"
  | "resume";
