export const siteConfig = {
  name: "Sai Maheswar Venkata - Full-Stack & AI Engineer",
  authorName: "Sai Maheswar",
  fullName: "Sai Maheswar Babbellapati Venkata",
  username: "saimaheswar",
  description:
    "Sai Maheswar Venkata - Full-stack and AI engineer with 5+ years of experience building Python web applications, backend systems, and machine learning services. Explore my projects, professional experience, and education.",
  url: "https://portfolio-smoky-phi-97.vercel.app",
  links: {
    twitter: "",
    github: "https://github.com/saimaheswar",
    linkedin: "https://linkedin.com/in/venkata-sai-b-79679v661",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/profile-img.jpg",
  iconIco: "/favicon.ico",
  logoIcon: "/profile-img.jpg",
  keywords: [
    "Sai Maheswar",
    "Sai Maheswar Venkata",
    "Full Stack Engineer",
    "AI Engineer",
    "Python Developer",
    "FastAPI Developer",
    "Software Engineer",
    "Machine Learning",
    "Backend Developer",
    "React Developer",
    "Data Engineering",
    "TypeScript",
    "Truist Bank",
    "NVIDIA",
    "Tech Portfolio",
  ],
};
